# Generated by Django 4.2.16 on 2026-08-24 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_follow_up_date_client_lead_status'),
        ('projects', '0002_project_contract_value_project_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('i_owe', 'Men qarzdorman (men olganman)'), ('they_owe', 'Menga qarzdor (men berganman)')], default='i_owe', max_length=10, verbose_name="Qarz yo'nalishi")),
                ('counterparty', models.CharField(max_length=200, verbose_name='Qarama-qarshi tomon (ism / kompaniya)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Qarz summasi')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="To'langan summa")),
                ('currency', models.CharField(choices=[('uzs', "UZS (so'm)"), ('usd', 'USD (dollar)'), ('rub', 'RUB (rubl)')], default='uzs', max_length=5, verbose_name='Valyuta')),
                ('reason', models.CharField(max_length=300, verbose_name='Sabab / izoh qisqacha')),
                ('notes', models.TextField(blank=True, verbose_name='Batafsil izoh')),
                ('debt_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Qarz olingan/berilgan sana')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="To'lov muddati")),
                ('status', models.CharField(choices=[('pending', "To'lanmagan"), ('partial', "Qisman to'langan"), ('paid', "To'liq to'langan"), ('overdue', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=12, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='clients.client', verbose_name='Mijoz (ixtiyoriy)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='projects.project', verbose_name='Loyiha (ixtiyoriy)')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['-debt_date', '-created_at'],
            },
        ),
    ]
