# Generated by Django 4.2.16 on 2026-08-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Boshqa')], default='telegram', max_length=20, verbose_name='Platforma')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas')], default='active', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='clients.client', verbose_name='Mijoz')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bots', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Botlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
