# Generated by Django 4.2.16 on 2026-09-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Telefon raqam (+998...)')),
                ('api_id', models.CharField(blank=True, max_length=50, verbose_name='API ID (my.telegram.org)')),
                ('encrypted_api_hash', models.TextField(blank=True, editable=False, verbose_name='Shifrlangan API Hash')),
                ('encrypted_session', models.TextField(blank=True, editable=False, verbose_name='Shifrlangan Session')),
                ('is_active', models.BooleanField(default=False, verbose_name='Avto-javob faol')),
                ('auto_reply_message', models.TextField(default="Salom! Hozir bandman. Murojaatingiz iftix0r.uz CRM tizimiga qabul qilindi. Tez orada siz bilan bog'lanaman.", verbose_name='Avto-javob matni')),
                ('reply_once_per_user', models.BooleanField(default=True, verbose_name='Bir foydalanuvchiga 1 marta yuborish')),
                ('ai_reply_enabled', models.BooleanField(default=False, verbose_name='AI (OpenAI) orqali javob berish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Userbot Sozlamasi',
                'verbose_name_plural': 'Userbot Sozlamalari',
            },
        ),
    ]
