# Generated by Django 4.2.16 on 2026-09-03 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_avatar_client_telegram_id'),
        ('bots', '0002_userbotconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='Telegram Message ID')),
                ('chat_id', models.BigIntegerField(db_index=True, verbose_name='Telegram Chat ID')),
                ('sender_id', models.BigIntegerField(blank=True, null=True, verbose_name='Sender ID')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='Yuboruvchi ismi')),
                ('is_outgoing', models.BooleanField(default=False, verbose_name='Chiquvchi xabar')),
                ('text', models.TextField(blank=True, verbose_name='Xabar matni')),
                ('media_type', models.CharField(choices=[('text', 'Matn'), ('photo', 'Rasm'), ('video', 'Video'), ('voice', 'Ovozli xabar'), ('document', 'Fayl'), ('other', 'Boshqa')], default='text', max_length=20, verbose_name='Media turi')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='telegram_chat_media/', verbose_name='Media fayli')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Tahrirlangan')),
                ('original_text', models.TextField(blank=True, verbose_name='Asl matn (tahrirdan oldingi)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name="Telegramda o'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqti')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_messages', to='clients.client', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Telegram Xabari',
                'verbose_name_plural': 'Telegram Xabarlari',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat_id', 'message_id'], name='bots_telegr_chat_id_5b680c_idx')],
            },
        ),
    ]
