# Generated by Django 4.2.16 on 2026-09-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name="O'qilgan"),
        ),
    ]
