# Generated by Django 4.2.16 on 2026-08-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('planning', 'Rejalashtirilmoqda'), ('in_progress', 'Jarayonda'), ('paused', "To'xtatilgan"), ('completed', 'Yakunlangan')], default='planning', max_length=20, verbose_name='Holati')),
                ('repo_url', models.URLField(blank=True, verbose_name='Repozitoriy havolasi')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
