# Generated by Django 4.2.16 on 2026-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kelishilgan summa'),
        ),
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Soatlik stavka'),
        ),
    ]
