# Generated by Django 4.2.16 on 2026-09-04 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_client_avatar_client_telegram_id'),
        ('projects', '0002_project_contract_value_project_hourly_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Fayl Sarlavhasi')),
                ('category', models.CharField(choices=[('brief', 'Texnik Topshiriq'), ('design', 'Dizayn / Figma'), ('contract', 'Hujjat / Shartnoma'), ('asset', 'Resurs / Fayllar'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Toifasi')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_files/', verbose_name='Fayl')),
                ('external_url', models.URLField(blank=True, verbose_name='Tashqi Havola (Figma, Drive, h.k.)')),
                ('is_public_to_client', models.BooleanField(default=True, verbose_name="Mijozga ko'rinsin")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='Loyiha')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Loyiha Fayli',
                'verbose_name_plural': 'Loyiha Fayllari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Hujjat Sarlavhasi')),
                ('doc_type', models.CharField(choices=[('contract', 'Shartnoma'), ('proposal', 'Tijorat Taklifi / Smeta'), ('spec', 'Texnik Topshiriq (ТЗ)')], default='contract', max_length=20, verbose_name='Hujjat Turi')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Hujjat Summasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Yuborilgan'), ('signed', 'Imzolangan / Qabul qilingan'), ('rejected', 'Rad etilgan')], default='draft', max_length=20, verbose_name='Holati')),
                ('content', models.TextField(verbose_name='Hujjat Matni (HTML / Markdown)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='Mijoz')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Shartnoma / Taklif',
                'verbose_name_plural': 'Shartnomalar va Takliflar',
                'ordering': ['-created_at'],
            },
        ),
    ]
