# Generated by Django 4.2.16 on 2026-08-24 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Maqsad')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('period', models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('quarterly', 'Choraklik'), ('yearly', 'Yillik'), ('custom', 'Boshqa')], default='monthly', max_length=12, verbose_name='Davr')),
                ('category', models.CharField(choices=[('business', 'Biznes'), ('personal', 'Shaxsiy'), ('learning', "O'rganish"), ('health', "Sog'liq"), ('finance', 'Moliya'), ('other', 'Boshqa')], default='business', max_length=12, verbose_name='Kategoriya')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Bajarildi'), ('failed', 'Bajarilmadi'), ('paused', "To'xtatilgan")], default='active', max_length=12, verbose_name='Holati')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Boshlanish sanasi')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0 dan 100 gacha. Vazifalar asosida avtomatik hisoblanadi.', verbose_name='Progress (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsadlar',
                'ordering': ['status', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='GoalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vazifa')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('todo', 'Bajarilmagan'), ('in_progress', 'Jarayonda'), ('done', 'Bajarildi'), ('skipped', "O'tkazib yuborildi")], default='todo', max_length=12, verbose_name='Holati')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default='medium', max_length=8, verbose_name='Muhimlik')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_tasks', to='goals.goal', verbose_name='Maqsad')),
            ],
            options={
                'verbose_name': 'Maqsad vazifasi',
                'verbose_name_plural': 'Maqsad vazifalari',
                'ordering': ['status', 'due_date', 'priority'],
            },
        ),
    ]
