# Generated by Django 4.2.16 on 2026-08-08 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('category', models.CharField(choices=[('server', 'Server'), ('domain', 'Domen'), ('subscription', 'Obuna'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Toifa')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Raqami')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Chiqarilgan sana')),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', 'Yuborilgan'), ('paid', "To'langan"), ('overdue', "Muddati o'tgan")], default='draft', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Mijoz')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Hisob-faktura',
                'verbose_name_plural': 'Hisob-fakturalar',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('method', models.CharField(choices=[('naqd', 'Naqd'), ('karta', 'Karta'), ('boshqa', 'Boshqa')], default='karta', max_length=20, verbose_name="To'lov usuli")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='clients.client', verbose_name='Mijoz')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Daromad',
                'verbose_name_plural': 'Daromadlar',
                'ordering': ['-date'],
            },
        ),
    ]
