# Generated by Django 4.2.16 on 2026-09-04 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, verbose_name="To'lov havolasi (Click/Payme)"),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Xizmat tavsifi')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Miqdor (soat yoki dona)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birlik narxi (UZS)')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Jami')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice', verbose_name='Invoys')),
            ],
            options={
                'verbose_name': 'Invoys satri',
                'verbose_name_plural': 'Invoys satrlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
