# Generated by Django 4.2.16 on 2026-09-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='app_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ilova versiyasi'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Oxirgi IP'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='OS versiyasi'),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='sdk_int',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Android SDK'),
        ),
        migrations.AddField(
            model_name='locationping',
            name='battery_charging',
            field=models.BooleanField(blank=True, null=True, verbose_name='Zaryadlanyapti'),
        ),
        migrations.AddField(
            model_name='locationping',
            name='battery_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Batareyka (%)'),
        ),
        migrations.AddField(
            model_name='locationping',
            name='network_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tarmoq turi'),
        ),
    ]
