# Generated by Django 4.2.16 on 2026-09-03 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratildi'), ('update', 'Yangilandi'), ('delete', "O'chirildi"), ('status', "Holat o'zgardi"), ('login', 'Tizimga kirdi'), ('logout', 'Tizimdan chiqdi'), ('export', 'Eksport qilindi'), ('upload', 'Fayl yuklandi'), ('other', 'Boshqa')], max_length=20, verbose_name='Harakat')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Obyekt')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Manzil')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit Yozuvi',
                'verbose_name_plural': 'Audit Jurnali',
                'ordering': ['-timestamp'],
            },
        ),
    ]
