# Generated by Django 4.2.16 on 2026-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Keyingi aloqa sanasi'),
        ),
        migrations.AddField(
            model_name='client',
            name='lead_status',
            field=models.CharField(choices=[('new', 'Yangi lead'), ('contacted', 'Aloqa qilingan'), ('proposal', 'Taklif yuborilgan'), ('active', 'Faol mijoz'), ('lost', "Yo'qotilgan")], default='new', max_length=20, verbose_name='Lead holati'),
        ),
    ]
