# Generated by Django 4.2.16 on 2026-09-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='clients/avatars/', verbose_name='Rasm / Avatar'),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram User ID'),
        ),
    ]
