# Generated by Django 4.2.16 on 2026-08-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nomi')),
                ('registrar', models.CharField(blank=True, max_length=150, verbose_name='Registrator')),
                ('expiration_date', models.DateField(verbose_name='Tugash sanasi')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Avtomatik uzaytirish')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Domen',
                'verbose_name_plural': 'Domenlar',
                'ordering': ['expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('provider', models.CharField(blank=True, max_length=150, verbose_name='Provayder')),
                ('specs', models.TextField(blank=True, verbose_name='Xarakteristika / izoh')),
                ('ssh_port', models.PositiveIntegerField(default=22, verbose_name='SSH port')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Serverlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Domen tanlanmasa, erkin nom kiriting', max_length=200, verbose_name='Nomi')),
                ('issuer', models.CharField(blank=True, max_length=150, verbose_name='Beruvchi (issuer)')),
                ('expiration_date', models.DateField(verbose_name='Tugash sanasi')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='infrastructure.domain', verbose_name='Domen')),
            ],
            options={
                'verbose_name': 'SSL sertifikat',
                'verbose_name_plural': 'SSL sertifikatlar',
                'ordering': ['expiration_date'],
            },
        ),
    ]
