"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lokal rivojlantirishda .env fayl orqali environment variable'larni o'rnatish
# uchun (DJANGO_SECRET_KEY, DJANGO_DEBUG, IFCODER_FERNET_KEY va h.k.). Fayl
# .gitignore'da — production'da esa cPanel/Passenger o'z environment
# variable'larini beradi, .env fayl kerak emas (mavjud bo'lmasa jim o'tkaziladi).
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lokal ishlab chiqish uchun fallback qiymat quyida qoladi; production'da
# DJANGO_SECRET_KEY environment variable orqali albatta almashtiring.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-n#hz%55&8k!y489-_@dq=$6-5ntn)el$-=x8j-q8@%1kjm@x)b',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Production serverda DJANGO_DEBUG=False environment variable sifatida o'rnatiladi.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'iftix0r.uz', 'www.iftix0r.uz',
    'yoshiqtidorlar.uz', 'www.yoshiqtidorlar.uz',
    'localhost', '127.0.0.1', 'testserver',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clients',
    'projects',
    'bots',
    'finance',
    'infrastructure',
    'content',
    'vault',
    'tasks',
    'debts',
    'goals',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'vault.middleware.TwoFactorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.alerts_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'public' / 'static'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard:home'

# API kalitlar va 2FA maxfiy kodlarini shifrlash uchun (vault app).
# DIQQAT: bu kalit yo'qolsa yoki almashtirilsa, mavjud vault yozuvlari butunlay
# o'qib bo'lmaydigan holga keladi. Production'da IFCODER_FERNET_KEY environment
# variable sifatida (cPanel/Passenger env orqali) o'rnatilishi qattiq tavsiya
# etiladi — quyidagi qiymat faqat lokal ishlab chiqish uchun fallback.
VAULT_FERNET_KEY = os.environ.get(
    'IFCODER_FERNET_KEY',
    'J_olCMzOvnbqcq4kf533E_qJx6dYSLq-6c_fVv2GPB0=',
)

# OpenAI yordamchisi uchun kalit. Uni .env yoki production environment'da bering.
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

# Production (DEBUG=False) uchun xavfsizlik sozlamalari — cPanel'dagi
# iftix0r.uz Let's Encrypt SSL bilan xizmat qilgani uchun HTTPS majburlanadi.
# Lokal (DEBUG=True) rivojlantirishga ta'sir qilmaydi.
if not DEBUG:
    # cPanel/Passenger'da Apache/LiteSpeed SSL'ni tashqarida tugatib, ilovaga
    # HTTP orqali uzatadi (reverse proxy). Shu header bo'lmasa, Django har doim
    # so'rovni "insecure" deb hisoblab, SECURE_SSL_REDIRECT bilan cheksiz
    # redirect halqasi hosil qiladi.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    CSRF_TRUSTED_ORIGINS = [
        'https://iftix0r.uz', 'https://www.iftix0r.uz',
        'https://yoshiqtidorlar.uz', 'https://www.yoshiqtidorlar.uz',
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
