# Generated by Django 4.2.16 on 2026-08-09 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('status', models.CharField(choices=[('todo', 'Bajarilmagan'), ('in_progress', 'Jarayonda'), ('done', 'Bajarilgan')], default='todo', max_length=20, verbose_name='Holati')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default='medium', max_length=20, verbose_name='Muhimlik')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.client', verbose_name='Mijoz')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['status', 'due_date'],
            },
        ),
    ]
