# Generated by Django 4.2.16 on 2026-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to_task_estimated_hours_timeentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Taxminiy soat'),
        ),
    ]
