# Generated by Django 4.2.16 on 2026-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='Ishlayaptimi?'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ishlangan soat'),
        ),
    ]
