# Generated by Django 4.2.16 on 2026-09-04 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('english', '🇬🇧 Ingliz Tili (IT & Business)'), ('coding', '💻 Dasturlash & Architecture'), ('business', '💼 Biznes & Monetizatsiya')], default='english', max_length=20, verbose_name='Toifa')),
                ('title', models.CharField(max_length=200, verbose_name='Mavzu Sarlavhasi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(default='📖', max_length=50, verbose_name='Emoji / Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('english', '🇬🇧 Ingliz Tili (IT & Business)'), ('coding', '💻 Dasturlash & Architecture'), ('business', '💼 Biznes & Monetizatsiya')], default='english', max_length=20, verbose_name='Toifa')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Qayd Matni (Markdown / Text)')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Teglar (vergul bilan)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_notes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Shaxsiy Qayd',
                'verbose_name_plural': 'Shaxsiy Qaydlar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('english', '🇬🇧 Ingliz Tili (IT & Business)'), ('coding', '💻 Dasturlash & Architecture'), ('business', '💼 Biznes & Monetizatsiya')], default='english', max_length=20, verbose_name='Toifa')),
                ('front_text', models.CharField(max_length=255, verbose_name="Savol / So'z / Tushuncha")),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='Talaffuz (Transkripsiya)')),
                ('back_text', models.TextField(verbose_name="Ma'nosi / Izohi / Yechim")),
                ('example_sentence', models.TextField(blank=True, verbose_name='Misol Matn / Senariy')),
                ('code_snippet', models.TextField(blank=True, verbose_name='Kod Namunasi')),
                ('is_mastered', models.BooleanField(default=False, verbose_name="O'zlashtirildi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='learning.topic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': "Lug'at / Kartochka",
                'verbose_name_plural': "Lug'atlar va Kartochkalar",
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AiTutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('english', '🇬🇧 English Conversation & Grammar'), ('coding', '💻 Code Review & Architecture'), ('business', '💼 Business & Client Pitching')], default='english', max_length=20, verbose_name='Rejim')),
                ('user_prompt', models.TextField(verbose_name='Foydalanuvchi Savoli')),
                ('ai_response', models.TextField(verbose_name='AI Javobi')),
                ('feedback', models.TextField(blank=True, verbose_name='Tahlil / Xatolar / Tavsiyalar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tutor_messages', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI Tutor Xabari',
                'verbose_name_plural': 'AI Tutor Xabarlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
