# Generated by Django 4.2.16 on 2026-08-08 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('encrypted_value', models.TextField(editable=False, verbose_name='Shifrlangan qiymat')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'API kalit',
                'verbose_name_plural': 'API kalitlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField(editable=False, verbose_name='Shifrlangan maxfiy kod')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_device', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': '2FA qurilma',
                'verbose_name_plural': '2FA qurilmalar',
            },
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(editable=False, max_length=200, verbose_name='Kod xesh')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='vault.totpdevice', verbose_name='Qurilma')),
            ],
            options={
                'verbose_name': 'Zaxira kod',
                'verbose_name_plural': 'Zaxira kodlar',
            },
        ),
    ]
