# Generated by Django 4.2.16 on 2026-09-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('body', models.TextField(verbose_name='Muammo tavsifi')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', "Ko'rib chiqilmoqda"), ('answered', 'Javob berildi'), ('closed', 'Yopildi')], default='open', max_length=20, verbose_name='Holati')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=20, verbose_name='Muhimlik darajasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='clients.client', verbose_name='Mijoz')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Tiket',
                'verbose_name_plural': 'Tiketlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Javob matni')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin javobiми')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tickets.ticket', verbose_name='Tiket')),
            ],
            options={
                'verbose_name': 'Tiket Javobi',
                'verbose_name_plural': 'Tiket Javoblari',
                'ordering': ['created_at'],
            },
        ),
    ]
