# Generated by Django 4.2.16 on 2026-09-03 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0002_ticket_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.ticket_attachment_path, verbose_name='Fayl')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketreply', verbose_name='Javob')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Tiket')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan')),
            ],
            options={
                'verbose_name': 'Tiket Fayli',
                'verbose_name_plural': 'Tiket Fayllari',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
